version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    env_file:
      - ./.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
